### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [jurca/szn-select#44]
Hi everyone.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by jurca** [comment]
Hello,

yes, the project is active (and used), there are just no active issues
requiring immediate attention at the moment.

Any help is appreciated.

pi 30. 12. 2022 o 3:49 Code Hangen ***@***.***> napísal(a):

**Comment by ghost** [comment]
Hi jurca.

> Hello,
> yes, the project is active (and used), there are just no active issues
requiring immediate attention at the moment.
> Any help is appreciated.

thank you for feedback. So... I'll close this question since you answered my question. So *have a great day* and I see how to help this open source project: szn-slect.
