### ISSUE TITLE
Complete Keyboard Accessibility

### ISSUE THREAD

**Issue by mohammedzamakhan** [jurca/szn-select#8]
I don't find the library to have full compatible keyboard accessibility.

When I focus the select dropdown with the keyboard, and try to type something, it does not do anything.

Expected:
It should try to find the option in the list, and try to select the one that matches closely.

**Comment by jurca** [comment]
Thank you for filing this issue! It appears I have overlooked this.

I will do my best to fix this before the end of Q2 2018.

**Comment by jurca** [comment]
Note to self: this issue is present when the VanillaAriaLabelledBySelect a11y broker is used (Firefox or macOS).

**Comment by jurca** [comment]
Fixed in 1.0.4. I had to make some compromises when the user is using Firefox due to the way Firefox handles accented characters typed using dead keys, but the UX impact should be minimal.

Please comment on this issue if you still find issues with this behavior. Thank you!
